USE CV;

DROP TABLE IF EXISTS CVData;

CREATE TABLE CVData (
  id          BIGINT    AUTO_INCREMENT PRIMARY KEY,
  type        VARCHAR(255) NOT NULL,
  description VARCHAR(255) NOT NULL,
  created     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);